apache/pekko-http

CONTRIBUTING.md
README.md
build.sbt
project/build.properties

Baby step toward switching from Akka to Pekko.

change to org.apache.pekko org id and update Github links to match apache/incubator-pekko-http

---

README.md

It's useful for potential users of Pekko to know what version of Akka it corresponds to. This PR adds that info to the README. It also adds the precise commit of the fork, since that's likely to be of interest to us and to others in the future.
I'd like to propose tagging that commit as well, as `akka-fork-base` or similar - do you agree this would be a good idea?

Record fork base commit and version in README

---

.git-blame-ignore-revs

Similar to pekko core, adds a `.git-blame-ignore-revs` which contains the hashes for the previous scalafmt commits.

Add git blame ignore revs

---

http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/ConnectionPoolBenchmark.scala
http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/ServerProcessingBenchmark.scala
http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/StreamServerProcessingBenchmark.scala
http-core/src/main/resources/reference.conf
http-core/src/test/scala/org/apache/pekko/http/ConfigSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/rendering/RequestRendererSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/rendering/ResponseRendererSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/HttpServerBug21008Spec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/HttpServerSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/HttpServerTestSetupBase.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/HttpServerWithExplicitSchedulerSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/WSClientAutobahnTest.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/WebSocketClientSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/WebSocketServerSpec.scala

Currently the `User-Agent` and server headers are set to `akka-http`, this PR changes it to `pekko-http`.

Rename akka-http user-agent plus server header to pekko-http

---

.github/workflows/nightly.yml
build.sbt
project/PekkoDependency.scala

which for now is only the main branch snapshot

run nightly test matrix against pekko versions

---

build.sbt

This used to carry the http2 implementation but we moved the implementation to http-core a long time ago. We continued publishing to avoid people missing the module but it doesn't seem to make sense to keep publishing for pekko-http.

disable publishing of http2-support module

---

.github/workflows/publish.yml

At least until we know that it will not create issues for the apache infrastructure.

publish nightlies only nightly and not for every main commit

---

.asf.yaml

Adds a github PR status check which disallows PR's from being merged if the code is not formatted. Note that its been verified that this works in another pekko module (see https://github.com/apache/incubator-pekko-sbt-paradox/blob/main/.asf.yaml#L28-L35)

Add github PR check to make sure code is formatted

---

project/PekkoDependency.scala

That fixes the nightly tests which only accidentally worked before and when fixing the akka->pekko prefix in f47c735e20d62fa58ce81e43cb4f5d82a1c9272b broke because "default" started to refer to pekko 1.0.0 which is not yet released.

make sure that no pekko version specified to build against is same as "default"

---

http-tests/src/test/scala/org/apache/pekko/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala

The problem is likely cold code together with a hiccup in the infrastructure. Even on my machine the tests when cold take ~500ms.
Fixes #84

tests: relax timeout in MultipartUnmarshallerSpec

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/parsing/HttpMessageParser.scala

These are somewhat genuine as we are using an `AnyRef` field for different value types for performance reasons (and in lack of cheap union types in Scala 2).

fix some warnings

---

docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingExamplesSpec.scala
project/Common.scala
project/Dependencies.scala

Recent Scala 2.13 versions deprecated the -target option which then fails the docs module compilation which has warnings as errors.
(Extracted from #81 because it was more complicated than expected)

update to Scala 2.13.10

---

build.sbt
project/plugins.sbt

self explanatory, confirmed it works locally i.e.
```
pekko-http > licenses
[info] http-caching / licenses
[info]  List((Apache-2.0,https://www.apache.org/licenses/LICENSE-2.0.html))
[info] http-jackson / licenses
[info]  List((Apache-2.0,https://www.apache.org/licenses/LICENSE-2.0.html))
[info] http-marshallers-java / licenses
[info]  List((Apache-2.0,https://www.apache.org/licenses/LICENSE-2.0.html))
[info] http-spray-json / licenses
[info]  List((Apache-2.0,https://www.apache.org/licenses/LICENSE-2.0.html))
[info] http-xml / licenses
[info]  List((Apache-2.0,https://www.apache.org/licenses/LICENSE-2.0.html))
[info] http-marshallers-scala / licenses
[info]  List((Apache-2.0,https://www.apache.org/licenses/LICENSE-2.0.html))
[info] http / licenses
[info] …
```

Add Apache to POM licenses field by updating sbt-apache-sonatype

---

project/plugins.sbt

This is a new plugin I'm working on. It will annotate compilation errors, warnings, and test failures on
the relevant files in Github Actions.
I added a test failure to show the result here.

use sbt-hackers-digest

---

build.sbt
docs/src/main/paradox/handling-blocking-operations-in-pekko-http-routes.md

Resolves:  https://github.com/apache/incubator-pekko-http/issues/42
I believe the original use of `@apidoc` was an oversight that just happened to work due to shadowing of package names, judging from what the text is saying I am quite sure its meant to be referring to `java.util.concurrent.ForkJoinPool` in which case direct linking to an external javadoc using `@javadoc` is what should be used.
I checked locally and the docs are render'ing as expected and I can confirm the link works (its `ForkJoinPool` is linking to https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ForkJoinPool.html)

Undo removal of doc ForkJoinPool mention

---

project/ValidatePullRequest.scala

To make sure that changes to the validation task really run all tests.

run full validation when github workflows change

---

.github/workflows/publish.yml

Otherwise, the version number will contain a timestamp because of the dirty workspace.

avoid making the workspace dirty by setting up .jvmpopts

---

LICENSE
NOTICE
legal/PekkoNotice.txt
project/AddMetaInfLicenseFiles.scala

* relates to #101 
* among our jars, only pekko-http-core needs additional text in license/notice
* all other jars built from this repo, will get the basic Apache license and the basic Pekko notice

add scala-collection-compat to license/notice

---

project/PekkoDependency.scala

Rather than using a static version for a snapshot, Pekko Http currently has code that tries to determine the latest snapshot version automatically by querying the snapshot repo (see https://github.com/apache/incubator-pekko-http/blob/main/project/PekkoDependency.scala#L100-L126). While this approach is a qol improvement when you are trying to work with Pekko http locally against some latest pekko snapshot, not having pekko-http release with a frozen version of a pekko snapshot is causing issues due to Pekko behaviour of not mixing different pekko core artifacts (which it inherited from Akka), i.e.
```
[error] Caused by: java.lang.IllegalStateException: You are using version 0.0.0+26623-85c2a469-SNAPSHOT of Apache Pekko, but it appears you (perhaps indirectly) also depend on older versions …
```

Freeze Pekko Snapshot

---

http-scalafix/scalafix-tests/src/test/scala/org/apache/pekko/http/fix/RuleSuite.scala

I found this when working on Scala 3 PR which also fixes this issue, but does it incorrectly so its a lot cleaner if I fix this separately.

Rename RuleSuite package from akka to pekko

---

project/AddMetaInfLicenseFiles.scala
project/Publish.scala
project/plugins.sbt

Updates sbt-apache-sonatype. Note that this new version renames `SonatypeApachePlugin` to `ApacheSonatypePlugin` to be consistent with the project name.

Update sbt-apache-sonatype and handle rename

---

docs/src/main/paradox/index.md
project/Dependencies.scala
project/LicenseReport.scala
project/ParadoxSupport.scala
project/plugins.sbt

Same as https://github.com/apache/incubator-pekko/pull/319 but for this project. Since pekko-http has a different doc layout, it is being placed in root under `Security Announcements!` i.e.
Feel free to approve the PR but please don't merge it until the Scala 3 PR gets merged, the Scala 3 PR is already outstanding and I don't want to complicate it more by creating more merge conflicts.

Integrate sbt-license-report

---

.git-blame-ignore-revs

Add the formatting commit from https://github.com/apache/incubator-pekko-http/pull/154 to `.git-blame-ignore-revs`

Add javafmt to .git-blame-ignore-revs

---

project/Doc.scala

Fixes a regression introduced in https://github.com/apache/incubator-pekko-http/pull/150 and also removed a duplicate line which was an oversight.

Cleanup and fix regressions for Scaladoc

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/parsing/HttpHeaderParser.scala
project/Dependencies.scala

Resolves: https://github.com/apache/incubator-pekko-http/issues/103
This PR updates to the latest released Parboiled2 which aside from supporting Scala 3.3 LTS also contains all of the upstreamed performance fixes aside from https://github.com/sirthias/parboiled2/pull/418 which @jrudolph solved within pekko-http at https://github.com/jrudolph/incubator-pekko-http/commit/67f46c3e5afbd1086aae5ef4eade5d9b831540ac , that specific commit has been cherry picked onto this PR.

Update parboiled apply performance fix

---

docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala
docs/src/test/scala/docs/http/scaladsl/server/directives/SchemeDirectivesExamplesSpec.scala
project/CopyrightHeader.scala
project/Dependencies.scala

Unwraps single string interpolation i.e. `s"${something}"` into `s"$something"`. Make sure to do a rebase merge of this PR because I need to add its commit to `.git-blame-ignore-revs`

Unwrap single string interpolation syntax

---

http/src/main/scala/org/apache/pekko/http/scaladsl/server/directives/FileUploadDirectives.scala

`java.io.File.createTempFile` creates files on Linux that are readable by everyone, we should be using `java.nio.Files.createTempFile` instead.

Use java NIO to create temp file

---

http/src/main/scala/org/apache/pekko/http/scaladsl/server/directives/FileUploadDirectives.scala

Getting
```
Error: Exception in thread "Thread-2529" java.nio.file.NoSuchFileException: /tmp/pekko-http-upload8380523090196242169.tmp
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
at java.nio.file.Files.delete(Files.java:1126)
```
from https://github.com/apache/incubator-pekko-http/actions/runs/5177204456/jobs/9327024671?pr=171

Replaces Files.delete with Files.deleteIfExits

---

http/src/main/scala/org/apache/pekko/http/scaladsl/server/directives/FileUploadDirectives.scala

This should properly restore the old behaviour, i.e. before https://github.com/apache/incubator-pekko-http/pull/170 was merged. Manually creating shut down hooks can create leaks and `java.io.File.deleteOnExit` only creates a single shutdownhook and maintains an internal collection of files to be deleted.
Doesn't resolve https://github.com/apache/incubator-pekko-http/issues/175 but at least it removes the current problematic cases of it.

Use java.io.File.deleteOnExit

---

http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/headers/headers.scala

Pekko-Connectors S3 uses these constructors.
See https://github.com/apache/incubator-pekko-connectors/pull/167
Scala 3 is stricter about private and package private access.

make Content-Type and Content-Length constructors accessible in pekko packages

---

http/src/main/scala/org/apache/pekko/http/scaladsl/coding/GzipCompressor.scala

```
[warn] /Users/pj.fanning/code/incubator-pekko-http/http/src/main/scala/org/apache/pekko/http/scaladsl/coding/GzipCompressor.scala:75:23: local var crc32 in <$anon: GzipDecompressor.this.ParsingLogic> is never updated: consider using immutable val
[warn]     private[this] var crc32: CRC32 = new CRC32
```

compile warning about var that could be a val

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/ProtocolSwitch.scala

saw this declaration when investigating #183 
I'm not sure why the `logic` var was added. I appears to be unused. No compile or test issues occurred after removing this line.

remove unused variable

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/ProtocolSwitch.scala

* relates to https://github.com/apache/incubator-pekko-http/issues/183
* simplifies the code, we don't really need the unapply

avoid unapply due to issue reported by Play team (scala 3 only)

---

project/Common.scala

This PR is the equivalent of https://github.com/apache/incubator-pekko/pull/258 but for pekko-http. The context behind these changes are complicated (read the linked pekko PR for more detail) but long story short the `release` scalac flag for Scala 2 changed at some point. The original version of `release` flag (which the code currently in pekko-http was written for) only makes scalac produce JDK 8 bytecode but it ignores the JDK 8 runtime `rt.jar`. This is almost never what you want, so a the same flag was updated in later versions of Scala (see https://github.com/scala/scala/pull/9982) which also brings in the correct `rt.jar`, i.e. if you build a project using JDK 11 with the `-release:8` flag then not only will it produce JDK8 bytecode but it will also bring in JDK 8's `rt.jar`.
That …

Use release 8 scalac flag to allow building on JDK11+

---

build.sbt

As noted in the comments these options were needed for Parboiled but since we are now using upstream parboiled rather than manually inlined source (see https://github.com/apache/incubator-pekko-http/pull/14) the settings are no longer relevant.

Remove unneeded parser settings

---

http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/ByteStringSinkProbe.scala

Which was `private[pekko]` in pekko-actor and might be removed.
See https://github.com/apache/incubator-pekko/pull/427

core: remove use of PrettyByteString

---

.github/workflows/nightly.yml

Because ``++3` isn't supported by the sbt cross-building parser.

build: fix nightly scala 3 compilation

---

docs/src/main/paradox/client-side/host-level.md
docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala

@kazuhiro if you could provide an alternate link for the broken one, we will use it
https://kazuhiro.github.io/scala/akka/akka-http/akka-streams/2016/01/31/connection-pooling-with-akka-http-and-source-queue.html

remove broken link from docs - cannot find another link that works

---

NOTICE
build.sbt
docs/src/main/paradox/common/cors.md
docs/src/main/paradox/common/index.md
docs/src/main/paradox/configuration.md
docs/src/main/paradox/migration-guide/index.md
docs/src/test/java/docs/http/javadsl/server/cors/CorsServerExample.java
docs/src/test/scala/docs/http/scaladsl/server/cors/CorsServerExample.scala
http-bench-jmh/src/main/scala/org/apache/pekko/http/cors/CorsBenchmark.scala
http-cors/src/main/java/org/apache/pekko/http/cors/javadsl/model/HttpHeaderRange.java
http-cors/src/main/java/org/apache/pekko/http/cors/javadsl/model/HttpHeaderRanges.java
http-cors/src/main/java/org/apache/pekko/http/cors/javadsl/model/HttpOriginMatcher.java
http-cors/src/main/resources/reference.conf
http-cors/src/main/scala/org/apache/pekko/http/cors/CorsJavaMapping.scala
http-cors/src/main/scala/org/apache/pekko/http/cors/javadsl/CorsDirectives.scala
http-cors/src/main/scala/org/apache/pekko/http/cors/javadsl/CorsRejection.scala
http-cors/src/main/scala/org/apache/pekko/http/cors/javadsl/settings/CorsSettings.scala
http-cors/src/main/scala/org/apache/pekko/http/cors/scaladsl/CorsDirectives.scala
http-cors/src/main/scala/org/apache/pekko/http/cors/scaladsl/CorsRejection.scala
http-cors/src/main/scala/org/apache/pekko/http/cors/scaladsl/model/HttpHeaderRange.scala
http-cors/src/main/scala/org/apache/pekko/http/cors/scaladsl/model/HttpOriginMatcher.scala
http-cors/src/main/scala/org/apache/pekko/http/cors/scaladsl/settings/CorsSettings.scala
http-cors/src/main/scala/org/apache/pekko/http/cors/scaladsl/settings/CorsSettingsImpl.scala
http-cors/src/test/scala/org/apache/pekko/http/cors/CorsDirectivesSpec.scala
http-cors/src/test/scala/org/apache/pekko/http/cors/scaladsl/model/HttpOriginMatcherSpec.scala
http-cors/src/test/scala/org/apache/pekko/http/cors/scaladsl/settings/CorsSettingsSpec.scala
project/Dependencies.scala

This PR adds pekko-http-cors support to pekko-http via the merge of akka-http-cors/pekko-http-cors (see https://github.com/lomigmegard/pekko-http-cors/issues/33). Notable points
* Legal disclaimers have been added (both to the root `LEGAL` file and to the `META-INF` jar indicating that the code was granted to ASF via SGA)
* The code is exactly the same as https://github.com/lomigmegard/pekko-http-cors with the expected package/import changes with these exceptions
* One breaking code change where `org.apache.pekko.http.cors.javadsl.settings.CorsSettings.getMaxAge` was changed from `Optional[Long]` to `OptionalLong` since this is consistent within the rest of the Akka/Pekko ecosystem (and is also idiomatic for Java use)
* A non breaking change where explicit return types where added to the …

Add pekko-http-cors module

---

project/AddMetaInfLicenseFiles.scala
project/LicenseReport.scala
project/build.properties

relates to https://github.com/apache/incubator-pekko/pull/474

use standard license on new files

---

docs/src/main/paradox/release-notes/index.md

may not be the final version - but I'd like to link to these notes instead of the [cwiki draft notes](https://cwiki.apache.org/confluence/display/PEKKO/Pekko+HTTP+Release+Notes) in our emails about RC votes and release announcements

add 1.0.0 release notes

---

.github/workflows/publish.yml

Resolves: https://github.com/apache/incubator-pekko-http/issues/216
The code which generates the api mappings for documentation originates from sbt-api-mappings. sbt-api-mappings tries to calculate the JDK version and if the calculated version is less than 11 it uses the broken reference as described in the issue, i.e.
https://github.com/ThoughtWorksInc/sbt-api-mappings/blob/5b1e4f11647421d287d3a26ed7fb077474ea7a3e/src/main/scala/com/thoughtworks/sbtApiMappings/BootstrapApiMappings.scala#L30-L44
Setting JDK 11 for publishing docs should be enough and its likely this is one of the reason why pekko-http core requires JDK 11 specifically for their documentation generation as well.

Fix broken generated java unidoc mappings

---

docs/src/main/paradox/release-notes/index.md

Due to a missing newline the list of dependency upgrades is not being rendered correctly.
See https://pekko.apache.org/docs/pekko-http/current/release-notes/index.html#1-0-0

Update release-notes/index.md (missing newline before bulleted list)

---

.github/workflows/publish.yml

This reverts commit 610348328dd3ece1f83f8dad13c46af24c54798d. See https://github.com/apache/incubator-pekko-http/pull/204#discussion_r1265279415 for context.

Revert "Fix broken generated java unidoc mappings"

---

README.md

* turns out we need to use java 8 to do the doc build
* mention `sbt testQuick` like incubator-pekko docs do

update build details

---

docs/src/main/paradox/assets/js/scrollToFragment.js

It was not used any more, but more importantly it does not seem to be necessary any more, as the underlying bug in Firefox seems to be fixed by now.
See https://github.com/lightbend/paradox/issues/443 for a history of the problem.

docs: remove left-over javascript file

---

LICENSE
http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/util/AsciiTreeLayout.scala
project/CopyrightHeader.scala

* part of -1 vote for RC
* sbt is now Apache licensed but back in sbt 0.12 days, it was BSD licensed

add license entry for sbt BSD license

---

http-core/src/test/scala/org/apache/pekko/http/impl/engine/parsing/ResponseParserSpec.scala

Seems to have happened quite often recently (mostly seen on Scala 3.3 Java 8 runs, not sure if that's something to investigate but likely not).

test: avoid frequent timeouts in ResponseParserSpec

---

LICENSE
NOTICE

* relates to #250 
* http-tests module is not published as a jar, so no need to worry about getting a tailored LICENSE/NOTICE included in its jar

update license and notice with akka-see license/notice

---

LICENSE

Base64Parsing is from parboiled2.
https://github.com/apache/incubator-pekko-http/blob/38ff8037a5677a47a652330af407e96cc78f98e7/http-core/src/main/scala/org/apache/pekko/http/impl/model/parser/Base64Parsing.scala
We have removed a lot of parboiled2 code from pekko-http but Base64Parsing is still there - although only some of its code is used.
[parboiled2](https://github.com/sirthias/parboiled2) has no NOTICE file.
relates to #249

add parboiled2 license

---

project/CopyrightHeader.scala

closes https://github.com/apache/incubator-pekko-http/issues/244
```
>  sbt 'show http/headerSources' | tail -n 10
[info] * /Users/krrrr38/dev/src/github.com/apache/incubator-pekko-http/http/src/main/scala/org/apache/pekko/http/scaladsl/server/directives/FileAndResourceDirectives.scala
[info] * /Users/krrrr38/dev/src/github.com/apache/incubator-pekko-http/http/src/main/scala/org/apache/pekko/http/scaladsl/marshalling/PredefinedToEntityMarshallers.scala
[info] * /Users/krrrr38/dev/src/github.com/apache/incubator-pekko-http/http/src/main/boilerplate/org/apache/pekko/http/scaladsl/server/directives/FormFieldDirectivesInstances.scala.template
[info] * /Users/krrrr38/dev/src/github.com/apache/incubator-pekko-http/http/src/main/boilerplate/org/apache/pekko/http/scaladsl/server/directives/Paramet …
```

build: sbt-header resolves boilerplace template files

---

CONTRIBUTING.md
README.md

note about h2spec and Mac Silicon

---

docs/src/main/paradox/examples-and-extensions.md

* pekko-http-cors is now part of Apache Pekko

update list of 3rd party jars

---

build.sbt
http-core/src/test/scala/org/apache/pekko/testkit/PekkoSpec.scala
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/H2SpecIntegrationSpec.scala
project/Dependencies.scala
project/Untar.scala

All test cases were reexported using `h2spec --dryrun` and a new
parser to group and select test cases was introduced.
After all, this way allowed more test cases to be enabled.
Based on and superseding #263
Fixes #262.
Can you check if this version works for you, @lomigmegard (you might have to `clean` in `http2-tests` submodule, to make space for the new `h2spec` binary).

Make h2spec 2.6.0 work

---

project/PekkoDependency.scala

Updates Pekko to 1.0.1. Also reverts `mainSnapshot` to what the original version should be now that we have a valid Pekko release

Set determineLatestSnapshot to properly resolve latest release

---

http-core/src/main/scala/org/apache/pekko/http/javadsl/Http.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/Http.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/headers/headers.scala

* We do this when the version number relates to a previous Akka HTTP release.
* We have it in most places but a few were missed

prefix deprecation versions with Akka HTTP

---

.github/workflows/validate-and-test.yml
docs/src/test/java/docs/http/javadsl/server/cors/CorsServerExample.java
http-tests/src/test/java/org/apache/pekko/http/javadsl/server/JavaTestServer.java
http-tests/src/test/java/org/apache/pekko/http/javadsl/server/directives/RouteDirectivesTest.java

The CI check for java code ended up not checking that test sources were formatted so this PR fixes. Make sure to let me rebase and merge because I need to add the commit to `.git-ignore-blame-revs`

Run javafmt check all

---

project/PekkoDependency.scala

problems with #294 
* I added a stray `"` into the regex
* the Group match has to handle 3 extra subgroups that the regex change brings in
* for `1.1.0-M0+22-4f570ea2-SNAPSHOT`, the 3 extra subgroups are `-M0`, `-M`, `0`
* if there is no `-M0` (or `-RC0`), the extra subgroups are all null
* the sorting will do for now but it doesn't take into account whether the tag is M or RC and there are other problems
* I did play around with sbt.librarymanagement.VersionNumber but it doesn't have a comparator (or scala.Ordering implementation).
* I will try this again to see if I can create my own comparator for sbt.librarymanagement.VersionNumber
* using this PR to get the build working for now
* I have tested these changes on my laptop

fix snapshot check

---

build.sbt
project/Jvm.scala
project/MultiNode.scala
project/SbtMultiJvm.scala
project/plugins.sbt

Just copy code from pekko, better to submit this upstream, will do later.

!sbt Use multiJvmPlugin from pekko.

---

docs/src/test/java/docs/http/javadsl/server/directives/MiscDirectivesExamplesTest.java
docs/src/test/scala/docs/http/scaladsl/server/directives/MiscDirectivesExamplesSpec.scala
http-core/src/main/java/org/apache/pekko/http/javadsl/model/StatusCodes.java
http-core/src/main/scala/org/apache/pekko/http/impl/engine/parsing/HttpRequestParser.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/server/HttpServerBluePrint.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/StatusCode.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/HttpServerSpec.scala
http-tests/src/test/java/org/apache/pekko/http/javadsl/server/directives/MiscDirectivesTest.java
http-tests/src/test/java/org/apache/pekko/http/javadsl/server/directives/RouteDirectivesTest.java
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/SizeLimitSpec.scala
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/MiscDirectivesSpec.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/server/ExceptionHandler.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/server/RejectionHandler.scala

I think the naming changed in RFC 9110, see https://www.rfc-editor.org/rfc/rfc9110.html#name-413-content-too-large and https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content.

Update naming for status codes 413 and 422

---

parsing/src/main/scala-2/org/apache/pekko/http/ccompat/pre213macro.scala
parsing/src/main/scala-2/org/apache/pekko/http/ccompat/since213macro.scala

I started working on macros recently and when browsing through pekko-http I noticed that we are throwing exceptions rather than `c.abort` which is what you are intended to use in unhandled macro cases (`c.abort` contains information about macro expansion such as the current macro position which is helpful for the error message).

Use c.abort in macro error cases

---

project/plugins.sbt

cherry pick 0652813b506b2b921de00905facdddd869faf79b

remove jcenter - it is deprecated (#339)

---

.github/workflows/nightly.yml
project/PekkoDependency.scala

* adjusts the tagNumber logic to treat build numbers without an RC or M tag as newer than ones that have them
* example
```
sbt -Dpekko.http.build.pekko.version=1.0.x package
```

allow test with pekko 1.0.x snapshot

---

http-core/src/test/scala/org/apache/pekko/http/impl/util/PekkoSpecWithMaterializer.scala

forward fit of #351 - the other changes in 351 are already in main branch

no need for casting to ActorMaterializer

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/PoolInterface.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpEntity.scala
http-core/src/test/scala/org/apache/pekko/http/impl/util/PekkoSpecWithMaterializer.scala

* these changes were taken from #347 but I don't want to backport all of that
* see also https://github.com/apache/incubator-pekko-http/pull/352
* ActorMaterializer is deprecated and it would be good not to assume all Materializers are ActorMaterializer

no need to cast to ActorMaterializer

---

http-compatibility-tests/src/test/scala/org/apache/pekko/http/scaladsl/HostConnectionPoolCompatSpec.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/PoolMasterActor.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/pool/SlotState.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/server/ServerTerminator.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/ServerBinding.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/ConnectionPoolSettings.scala
http-core/src/test/scala/org/apache/pekko/http/impl/model/parser/HttpHeaderSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/util/PekkoSpecWithMaterializer.scala
http-core/src/test/scala/org/apache/pekko/http/scaladsl/ClientServerSpec.scala
http-core/src/test/scala/org/apache/pekko/http/scaladsl/GracefulTerminationSpec.scala
http-core/src/test/scala/org/apache/pekko/testkit/PekkoSpec.scala
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/RoutingSpec.scala
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/IllegalHeadersIntegrationSpec.scala
http/src/main/scala/org/apache/pekko/http/javadsl/marshalling/Marshaller.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/marshalling/Marshaller.scala
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2ClientSpec.scala
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2PersistentClientSpec.scala
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2ServerSpec.scala
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/RequestParsingSpec.scala

* raised https://github.com/apache/incubator-pekko-http/issues/355 for follow up
* some issue links were incorrectly updated to point to pekko-http issues but the pekko links don't work

fix more akka naming

---

http-core/src/test/scala/org/apache/pekko/http/impl/engine/parsing/RequestParserSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/rendering/RequestRendererSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/rendering/ResponseRendererSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/HttpServerSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/PrepareRequestsSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/EchoTestClientApp.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/WSClientAutobahnTest.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/WSServerAutobahnTest.scala
http-core/src/test/scala/org/apache/pekko/http/impl/util/One2OneBidiFlowSpec.scala
http-core/src/test/scala/org/apache/pekko/http/impl/util/StreamUtilsSpec.scala
http-core/src/test/scala/org/apache/pekko/http/scaladsl/ClientSpec.scala
http-core/src/test/scala/org/apache/pekko/http/scaladsl/TestClient.scala
http-core/src/test/scala/org/apache/pekko/http/scaladsl/TightRequestTimeoutSpec.scala

there are still some left but these are the easy ones to remove

remove more uses of ActorMaterializer

---

http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpMessage.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/client/NewConnectionPoolSpec.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/server/ContentNegotation.scala

This PR fixes some of the compilation errors found in the Open Community Build for the nightly versions of Scala 3.4.x. 
It would allow the Scala compiler team to track any new regressions found in this project.

Fix compilation errors found in Scala3 Open Community Build

---

project/Dependencies.scala

https://mvnrepository.com/artifact/org.specs2/specs2-core
* most recent 4.x release
* simplifies the build - avoids having different versions depending on scala version

standardise on specs 4.20

---

http-bench-jmh/src/main/scala/org/apache/pekko/BenchTestSource.scala
http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/MessageToFrameRendererBenchmark.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/Http2Blueprint.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/ws/MessageToFrameRenderer.scala
http-core/src/main/scala/org/apache/pekko/http/impl/util/StreamUtils.scala
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/RequestParsingSpec.scala

Motivation:
Use the `statefulMap` instead when concating is not needed.
```
[info] Benchmark                                                Mode  Cnt         Score         Error  Units
[info] MessageToFrameRendererBenchmark.benchNewStreamedFrames  thrpt   10  25333318.747 锟斤拷 1293108.754  ops/s
[info] MessageToFrameRendererBenchmark.benchOldStreamedFrames  thrpt   10  20352150.287 锟斤拷 1563364.567  ops/s
```

=core Make use of statefulMap instead of statefulMapConcat.

---

build.sbt
project/VersionGenerator.scala
project/plugins.sbt

relates to #380 
* sbt-pekko-build 0.2.0 uses pekko 1.0.2 as the default
* VersionGenerator uses a minPekkoVersion value that is set to 1.0.0
* this means that the validation mentioned in #380 will allow all versions from Pekko 1.0.0 and up

build with pekko 1.0.2

---

http/src/main/scala/org/apache/pekko/http/javadsl/unmarshalling/Unmarshaller.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/unmarshalling/Unmarshaller.scala

This PR adds a `javadsl` equivalent of `org.apache.pekko.http.scaladsl.unmarshalling.Unmarshaller.UnsupportedContentTypeException` without breaking binary compatibility (you can confirm this by running `sbt mimaReportBinaryIssues`)
While the changes aren't as trivial as what would be considered ideal, they are necessary in order to not break MiMa. Of note is that the core data structure for the exception is being changed from Scala `Set`/`Option` to Java `Set`/`Optional`. Additionally the javadsl version of `UnsupportedContentTypeException` doesn't support Scala specific language features (i.e. `Product`/`Serializable`/`canEqual`).

Add UnsupportedContentTypeException javadsl

---

docs/src/main/paradox/common/cors.md

Have a look at https://pekko.apache.org/docs/pekko-http/current/common/cors.html and see the `@@@ div { .group-scala }` and similar other tags appearing. Spreading out the markdown seems to fix this issue on my local build.

try to fix scala/java issue with CORS page

---

docs/src/main/paradox/common/cors.md

see https://nightlies.apache.org/pekko/docs/pekko-http/main-snapshot/docs/common/cors.html#rejection

fix todo link in CORS doc

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/PoolMasterActor.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/pool/NewHostConnectionPool.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/Http2.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/server/HttpServerBluePrint.scala
http-core/src/main/scala/org/apache/pekko/http/impl/util/StreamUtils.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/Http.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/ServerBinding.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/ServerBuilder.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/Http.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/WebSocketIntegrationSpec.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/RequestContext.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/BasicDirectives.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/RouteDirectives.scala

`ExecutionContexts.sameThreadExecutionContext` is deprecated and `ExecutionContexts.parasitic` should be used instead (one is an alias for the other).

Replace ExecutionContexts.sameThreadExecutionContext with parasitic

---

http/src/main/scala/org/apache/pekko/http/javadsl/server/RoutingJavaMapping.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/BasicDirectives.scala

This PR is a response to https://github.com/apache/incubator-pekko/pull/894, specifically rather than using the Java designed converter methods within Scala sources we use the Scala ones so that when the project is compiled with Scala 3 it gets inlined.
Note that in the case of `BasicDirectives`, the reason why pekko-http was using the designated Java methods in the first place is due to ambiguous implicit imports which is why `CompletionStageOps` is being used rather than the typical use of extension methods within `implicit class`.

Use designated Scala methods for converter utils

---

.scala-steward.conf

Incase we ever end up using scala steward on 1.0.x so we don't create unnecessary PR's

Add and fix sbt paradox update ignore

---

.scala-steward.conf
http-marshallers-java/http-jackson/src/main/java/org/apache/pekko/http/javadsl/marshallers/jackson/Jackson.java
http-marshallers-java/http-jackson/src/main/resources/reference.conf
http-marshallers-java/http-jackson/src/test/java/org/apache/pekko/http/javadsl/marshallers/jackson/JacksonTest.java
project/Dependencies.scala

add config support for setting read and write constraints

pekko-http-jackson: upgrade jackson to 2.16

---

.github/workflows/dependency-graph.yml

Resolves: https://github.com/apache/incubator-pekko-http/issues/433 , see https://github.com/scalacenter/sbt-dependency-submission/issues/156#issuecomment-1903956426

Fix dependency-submission with invalid module

---

http-core/src/main/resources/reference.conf

In older versions of Akka, there was a separate jar. This comment makes no sense in Pekko.

pekko-http2-support is part of pekko-http-core

---

http-core/src/main/resources/reference.conf

cherry pick 0dcc3466115d659d6a79330536e52cfbd53565d6 #437

pekko-http2-support is part of pekko-http-core (#437)

---

http-tests/src/test/resources/dirWithLink/linked-dir
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/FileAndResourceDirectivesSymlinkSpec.scala

* rework existing symlink test so that it creates the link itself (and removes it) - in /tmp folder for duration of test
* aim is to get 1.0.x ready for 1.0.1-RC2 - will forward fit after it is merged
#275, #444

rework symlink test

---

build.sbt

This is being done because currently its actually disabling the [knob](https://github.com/pjfanning/sbt-pekko-build/blob/main/src/main/scala/com/github/pjfanning/pekkobuild/PekkoInlinePlugin.scala#L56) that allows you to toggle inlining locally incase you want to diagnose whats going on.
It also defeats the whole purpose of having the inliner configuration in sbt-pekko-build in the first place, i.e. the point of sbt-pekko-build is to centralize common build logic to avoid boilerplate and keep things consistent between Pekko projects.
Note that I am also currently in the process of adding a log statement to sbt-pekko-build which will print whether the inliner is enabled or not to avoid surprises for developers, just waiting on https://discord.com/channels/632150470000902164/9226000509898752 …

Remove explicit inliner setting override

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/hpack/ByteStringInputStream.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/coding/DeflateCompressor.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/coding/GzipCompressor.scala
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2FrameHpackSupport.scala

only safe to use toArrayUnsafe when you know that you are not mutating the array
the advantage is that you safe on having to clone the inner array that the ByteString has
there might be 1 or 2 more places that we could update in pekko-http too

use ByteString.toArrayUnsafe where it is safe to do so and improves performance

---

.github/workflows/headers.yml
.github/workflows/link-validator.yml
.github/workflows/nightly.yml
.github/workflows/publish-1.0-docs.yml
.github/workflows/publish-1.0-snapshots.yml
.github/workflows/publish.yml
.github/workflows/validate-and-test.yml

to pick up
* https://github.com/coursier/cache-action/releases/tag/v6.4.5
* setup-java v4

upgrade CI actions

---

.scala-steward.conf

Pins the sbt-paradox/sbt-paradox-project-info versions since we can use the entire 0.9.x series (it being compiled against JDK 8).
Also removes `sbt-paradox-apidoc` from the ignore list since we are free to update this (note that `sbt-paradox-apidoc` was recently updated to latest version without any issues)

Remove apidoc from ignore and pin paradox versions

---

build.sbt
scripts/link-validator.conf

japi is for javadoc - api is for scaladoc - we have them the wrong way around in build.sbt
relates to https://github.com/apache/incubator-pekko-http/issues/493

fix api/japi links in build.sbt

---

.scala-steward.conf
project/Dependencies.scala

Latest Scala 2.13.13 breaks genjavadoc with means our doc publishing is broken, see https://github.com/lightbend/genjavadoc/issues/347, https://github.com/scala/bug/issues/12966 and https://github.com/apache/incubator-pekko-http/actions/runs/8126952015 for the CI failing

Revert to scala 2.13.12 due to regression with genjavadoc + Scala 2.13.13

---

.scala-steward.conf
project/plugins.sbt

Reverts apache/incubator-pekko-http#499
the downgrade of Scala 2.13 is now leading to failures on dependency graph job - see https://github.com/apache/incubator-pekko-http/actions/runs/8129865838

Revert "Update sbt-scalafix, scalafix-core to 0.12.0"

---

http-marshallers-java/http-jackson/src/main/java/org/apache/pekko/http/javadsl/marshallers/jackson/Jackson.java
http-marshallers-java/http-jackson/src/main/resources/reference.conf
http-marshallers-java/http-jackson/src/test/java/org/apache/pekko/http/javadsl/marshallers/jackson/JacksonTest.java

see https://github.com/apache/pekko/pull/1192

support jackson buffer recycler

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/parsing/HttpMessageParser.scala
http-core/src/test/scala/org/apache/pekko/http/impl/engine/parsing/RequestParserSpec.scala

Continue parsing HTTP chunk size up until Int.MaxValue so the actual size of the chunk can be logged if it exceeds the configured max chunk size.

Parse entire HTTP chunk size #396

---

http-core/src/test/scala/org/apache/pekko/http/impl/engine/parsing/RequestParserSpec.scala

This is a followup of #528
The current test goes over the configured max chunk size when parsing the last hex char. The spirit of the code is to continue parsing the size even if we've already gone over the max chunk size. To actually test this we need to make sure another char follows after we've gone over the max chunk size.

Improve too large chunk size test

---

project/Untar.scala

```
project/Untar.scala:34:25: method getNextTarEntry in class TarArchiveInputStream is deprecated
[warn]         var entry = tis.getNextTarEntry
```

fix deprecation warning in Untar.scala

---

http-testkit/src/test/scala/org/apache/pekko/http/scaladsl/testkit/ScalatestRouteTestSpec.scala

I think this reference was changed in a mass search and replace, but it now links to the GitHub 404 page.

Fix reference to an akka-http GitHub issue

---

http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2FrameHpackSupport.scala

pekko-http already has a class that optimises getting an InputStream for a ByteString. We should use it for consistency.
I know this is test code but If anything, this improves our test coverage of ByteStringInputStream

use ByteStringInputStream

---

docs/src/test/scala/docs/http/scaladsl/Http2ClientApp.scala
docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala

OverflowStrategy.dropNew has been deprecated
Use Source.queue

Use Source.queue

---

build.sbt
http-core/src/main/scala/org/apache/pekko/http/scaladsl/Http.scala
http-testkit-munit/src/main/scala/org/apache/pekko/http/scaladsl/testkit/munit/MunitRouteTest.scala
http-testkit-munit/src/main/scala/org/apache/pekko/http/scaladsl/testkit/munit/MunitTestFramework.scala
http-testkit-munit/src/test/scala/org/apache/pekko/http/scaladsl/testkit/munit/MunitRouteTestSpec.scala
project/Dependencies.scala

Applying this PR will add support for testing routes with MUnit.

Add munit test framework

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/hpack/ByteStringInputStream.scala

* ByteString.asInputStream is only in Pekko 1.1 - so if you use this code with Pekko 1.0, the MethodHandle will not work and the code falls back to existing ByteArrayInputStream

use optimised ByteString.asInputStream

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/hpack/ByteStringInputStream.scala

This reverts commit 03f128907cf55ff2e1777ee0b6fc75d58c7188b9.
see #549

Revert "use optimised ByteString.asInputStream (#539)"

---

http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala

see #558 
the issue may be down to classloading changes in sbt 1.10.0 - only recent change in this repo
still, the testRoot val seems tidier and works fine when tested on my laptop

fix issue in listDirectoryContents test

---

http-core/src/main/scala/org/apache/pekko/http/impl/model/parser/HeaderParser.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpHeader.scala
http-core/src/test/scala/org/apache/pekko/http/impl/model/parser/HttpHeaderSpec.scala

fix parse broken when header value is null

---

http-core/src/main/scala/org/apache/pekko/http/impl/model/parser/HeaderParser.scala
http-core/src/test/scala/org/apache/pekko/http/impl/model/parser/HttpHeaderSpec.scala

cherry pick 41e4f46e35f4ef90a30b5d6a924413a83c3fa110 #575
issue https://github.com/apache/pekko-http/issues/574

fix parse broken when header value is null (#575)

---

docs/src/main/paradox/release-notes/releases-1.1.md
http-core/src/main/resources/reference.conf
http-core/src/test/resources/reference.conf
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/H2SpecIntegrationSpec.scala

References: https://github.com/apache/pekko-http/issues/422
Still need to update tests as per @jrudolph original comment, i.e.
> That broke lots of tests that probably didn't automatically propagate closing so they now fail while waiting for the now ten times longer cancellation times... (Might still might sense to "just" fix those tests)

Increase stream-cancellation-delay default to 1000 millis

---

http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpCharset.scala
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/marshalling/MarshallingSpec.scala
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/MarshallingDirectivesSpec.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/marshalling/PredefinedToEntityMarshallers.scala

see #300 
I've added #585 to look into the XML case - this PR focuses on text/plain.

handle invalid accept-charset in requests - default to utf-8

---

docs/src/main/paradox/examples-and-extensions.md

* some more extensions
* all the Akka HTTP equivalents are now listed in this doc (they all support Pekko now)

update extensions doc

---

docs/src/main/paradox/examples-and-extensions.md

cherry pick 174934938fae0858763ded0965fe0ecdfa4281c0 #593

update extensions doc (#593)

---

build.sbt

link to the version specific docs

don't link to 'current' pekko docs

---

build.sbt

cherry pick c8ea51c49b2c39d3369ba6f1e8343c46214f19f0 #603 
this fixes a link issue in our migration docs that point to a 'current' doc link that no longer works

don't link to 'current' pekko docs (#603)

---

docs/src/main/paradox/release-notes/releases-1.1.md
http-core/src/main/resources/reference.conf
http-core/src/test/resources/reference.conf
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/H2SpecIntegrationSpec.scala

Reverts apache/pekko-http#590
Still open for discussion. See https://lists.apache.org/thread/h59dphf5j20tzjwrm1z1c8olptnqrrhy

Revert "Increase stream-cancellation-delay default to 1000 millis"

---

.jvmopts

Had mem issues while publishing v1.1.0-RC1. This has been an ongoing issue with previous releases too.

increase xmx for sbt due to mem issues in build

---

project/build.properties
project/plugins.sbt

uptakes https://github.com/mdedetrich/sbt-apache-sonatype/pull/40
via https://github.com/pjfanning/sbt-pekko-build/pull/15
we don't really need the typesafe resolver any more either

uptake sbt-apache-sonatype release via sbt-pekko-build

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/Http2.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/Http2Blueprint.scala

In a similar vein to https://github.com/apache/pekko/pull/1489, this fixes Kamon instrumentation of http2 flows in pekko-http 1.1.+. (cf https://github.com/kamon-io/Kamon/pull/1362 , which fails on https instrumentation tests)

annotate some instrumented methods with @noinline

---

.github/workflows/dependency-graph.yml
.github/workflows/headers.yml
.github/workflows/link-validator.yml
.github/workflows/nightly.yml
.github/workflows/publish-1.0-docs.yml
.github/workflows/publish-1.0-snapshots.yml
.github/workflows/publish-1.1-docs.yml
.github/workflows/publish.yml
.github/workflows/validate-and-test.yml

We can no longer rely on sbt being pre-installed in CI envs.
https://eed3si9n.com/setup-sbt/
see broken jobs in https://github.com/apache/pekko-http/pull/618/checks
`ubuntu-latest` is now ubuntu-24 and as documented in the eed3si9n.com article, that does not have sbt pre-installed
we use a lot of different versions of ubuntu in our builds - change to use ubuntu 22 as a min

CI: install sbt

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/HttpMessageRendering.scala
http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/HttpMessageRenderingSpec.scala

I hit this case in a test and it threw. I am not sure if when `trailer.headers` is empty, it should return None or a parsed frame with empty headers but I figured the guard was there for a reason

Fix partial match

---

docs/src/main/paradox/release-notes/releases-1.0.md

issue seen in link validator runs

fix broken link (akka security)

---

docs/src/test/java/docs/http/javadsl/CustomMediaTypesExampleTest.java
http-core/src/main/mima-filters/1.2.x.backwards.excludes/content-media-type-value-string.backwards.excludes
http-core/src/main/scala/org/apache/pekko/http/javadsl/model/ContentType.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/model/MediaType.scala

Currently in the javadsl its not possible to get the string representation of the `Content-Type`/`Media-Type` because its only the scaladsl that implements the `value` function (via the `ValueRenderable` trait). This PR adds the `value` method to the core Java interfaces (the `render` method is anyways implemented in the subclasses hence why this PR is compiling without any additional changes)
As a workaround I currently have to do this (its in kotlin but should be understandable)
```kotlin
internal fun contentTypeToString(contentType: ContentType): String {
return when (contentType) {
is org.apache.pekko.http.scaladsl.model.ContentType ->
return contentType.value()
else -> throw RuntimeException("Unsupported content type: ${contentType::class.qualifiedName}")
}
}
```
This works because …

Get string representation of javadsl Content and Media Type

---

http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/Uri.scala
http-core/src/test/scala/org/apache/pekko/http/scaladsl/model/UriSpec.scala

`Uri.withQuery` receives a `Query` object, converts it to a string, and then calls the `Uri.copy` method which creates a new `Uri` object with the given query (The `Uri` class holds the query as an un-parsed string).
The `copy` method ends up in `queryString.map(new UriParser(_).parseRawQueryString())` which percent-encodes the query string.
As in this flow, the query string is converted from a `Query` object, it is always percent-encoded, so the additional encoding operation is unnecessary. We can skip it by replacing the call to `copy` with `createUnsafe`.

Optimized Uri.withQuery

---

.scala-steward.conf
http-marshallers-java/http-jackson/src/main/java/org/apache/pekko/http/javadsl/marshallers/jackson/Jackson.java
http-marshallers-java/http-jackson/src/main/resources/reference.conf
http-marshallers-java/http-jackson/src/test/java/org/apache/pekko/http/javadsl/marshallers/jackson/JacksonTest.java
project/Dependencies.scala

see https://github.com/apache/pekko/pull/1556
need to document the removal of lock-free recycler pool option (Jackson abandoned this) and max-token-count

jackson 2.18.2

---

.scala-steward.conf

we already use newer versions of scala-xml and specs2 than the scala steward pin is set to
* scala-xml 2.1.0: https://github.com/apache/pekko-http/blob/main/project/Dependencies.scala#L54
* specs2 4.20.3: https://github.com/apache/pekko-http/blob/main/project/Dependencies.scala#L81

remove old scala steward settings

---

.github/workflows/dependency-graph.yml
.github/workflows/format.yml
.github/workflows/headers.yml
.github/workflows/link-validator.yml
.github/workflows/nightly.yml
.github/workflows/publish-1.0-snapshots.yml
.github/workflows/publish-1.1-snapshots.yml
.github/workflows/publish-test-reports.yml
.github/workflows/publish.yml
.github/workflows/scala-steward.yml
.github/workflows/validate-and-test.yml

header depends on if the yml was added first for Pekko or if it is based on one that we inherited from Akka code

add source headers to CI files

---

.github/workflows/publish-1.2-docs.yml
docs/src/main/paradox/release-notes/index.md
docs/src/main/paradox/release-notes/releases-1.2.md

release vote passed
#680 fixes the CI issue that is unrelated to this PR's changes

release notes for 1.2.0

---

http-core/src/main/scala/org/apache/pekko/http/scaladsl/ClientTransport.scala

pekko 2.0.0 removes a lot of deprecated methods and it would be nice to tidy up pekko-http to avoid such methods

stop using deprecated method Flow.lazyInitAsync

---

http-core/src/main/java/org/apache/pekko/http/javadsl/model/headers/HttpCookie.java

causes a build warning when missing

add missing Deprecated annotation

---

http-core/src/main/scala/org/apache/pekko/http/scaladsl/ConnectionContext.scala
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/HeaderDirectivesSpec.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/unmarshalling/sse/ServerSentEventParser.scala

* Scala 3 compiler gives a compiler warning
```
Modifier final is redundant for this definition
```

remove `final object`

---

http-core/src/test/scala/org/apache/pekko/http/scaladsl/TestServer.scala

The fuzzing setting is set in the config - so this is not needed.
The API is deprecated and is being removed.

remove withFuzzing call in tests

---

http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/TelemetrySpiSpec.scala

The Source.actorRef used here is deprecated and due for removal - use the non-deprecated overload.

avoid deprecated method used in test code

---

http-core/src/test/java/org/apache/pekko/http/javadsl/WSEchoTestClientApp.java

Pekko 2 removes some of the Scala class support for the Java DSL to encourage Pure Java usages instead

avoid Scala classes in Java example

---

docs/src/test/java/docs/http/javadsl/server/HttpServerExampleDocTest.java

* a backport of doc example fix from #753 
* it is not ideal for our doc examples to rely on deprecated methods

avoid deprecated methods in docs example

---

http-caching/src/main/scala/org/apache/pekko/http/caching/LfuCache.scala
http-caching/src/main/scala/org/apache/pekko/http/caching/scaladsl/Cache.scala
http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/OutgoingConnectionBuilderImpl.scala
http-core/src/main/scala/org/apache/pekko/http/impl/util/JavaMapping.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/ClientTransport.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/Http.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/IncomingConnection.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/ServerBinding.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/ServerBuilder.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/model/ws/Message.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/Http.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpEntity.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpMessage.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/Multipart.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/ws/Message.scala
http-core/src/test/scala/org/apache/pekko/http/javadsl/model/MultipartsSpec.scala
http-tests/src/test/java/org/apache/pekko/http/javadsl/unmarshalling/sse/EventStreamUnmarshallingTest.java
http/src/main/java/org/apache/pekko/http/javadsl/coding/Coder.java
http/src/main/scala/org/apache/pekko/http/javadsl/server/RequestContext.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/RoutingJavaMapping.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/BasicDirectives.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/FutureDirectives.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/RouteAdapter.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/SecurityDirectives.scala
http/src/main/scala/org/apache/pekko/http/javadsl/unmarshalling/Unmarshaller.scala

now that we no longer support Scala 2.12 in main branch

use Scala Future Converters

---

docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java
docs/src/test/java/docs/http/javadsl/server/directives/BasicDirectivesExamplesTest.java
docs/src/test/java/docs/http/javadsl/server/directives/CachingDirectivesExamplesTest.java
docs/src/test/java/docs/http/javadsl/server/directives/TimeoutDirectivesExamplesTest.java
docs/src/test/java/docs/http/javadsl/server/directives/WebSocketDirectivesExamplesTest.java
http-caching/src/main/scala/org/apache/pekko/http/caching/javadsl/LfuCacheSettings.scala
http-core/src/main/java/org/apache/pekko/http/javadsl/TimeoutAccess.java
http-core/src/main/mima-filters/1.3.x.backwards.excludes/java-duration-support-javadsl.excludes
http-core/src/main/scala/org/apache/pekko/http/impl/engine/server/HttpServerBluePrint.scala
http-core/src/main/scala/org/apache/pekko/http/impl/settings/ClientConnectionSettingsImpl.scala
http-core/src/main/scala/org/apache/pekko/http/impl/settings/ConnectionPoolSettingsImpl.scala
http-core/src/main/scala/org/apache/pekko/http/impl/settings/WebSocketSettingsImpl.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/ClientConnectionSettings.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/ConnectionPoolSettings.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/Http2ClientSettings.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/Http2ServerSettings.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/ServerSettings.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/WebSocketSettings.scala
http-core/src/test/scala/org/apache/pekko/http/javadsl/model/MultipartsSpec.scala
http-testkit/src/main/scala/org/apache/pekko/http/javadsl/testkit/WSProbe.scala
http-tests/src/test/java/org/apache/pekko/http/javadsl/server/JavaTestServer.java
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/BasicDirectives.scala
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/TimeoutDirectives.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/unmarshalling/Unmarshaller.scala

* Forward fit of #780 
* there is some follow up work
* #782
* #783

Java duration in javadsl (#780)

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/server/HttpServerBluePrint.scala

* follow up to #780 
* an additional commit was added to #784 based on PR feedback from @He-Pin

remove ability to pass a null java timeout

---

docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java
docs/src/test/java/docs/http/javadsl/server/directives/TimeoutDirectivesExamplesTest.java
http-caching/src/main/mima-filters/2.0.x.backwards.excludes/javadsl-change-duration-return-types.excludes
http-caching/src/main/scala/org/apache/pekko/http/caching/javadsl/LfuCacheSettings.scala
http-caching/src/main/scala/org/apache/pekko/http/caching/scaladsl/LfuCacheSettings.scala
http-core/src/main/java/org/apache/pekko/http/javadsl/TimeoutAccess.java
http-core/src/main/mima-filters/1.3.x.backwards.excludes/java-duration-support-javadsl.excludes
http-core/src/main/mima-filters/2.0.x.backwards.excludes/javadsl-change-duration-return-types.excludes
http-core/src/main/scala/org/apache/pekko/http/impl/engine/server/HttpServerBluePrint.scala
http-core/src/main/scala/org/apache/pekko/http/impl/settings/ClientConnectionSettingsImpl.scala
http-core/src/main/scala/org/apache/pekko/http/impl/settings/ConnectionPoolSettingsImpl.scala
http-core/src/main/scala/org/apache/pekko/http/impl/util/JavaDurationConverter.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/ClientConnectionSettings.scala
http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/ConnectionPoolSettings.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/TimeoutAccess.scala
http-core/src/test/scala/org/apache/pekko/http/impl/util/JavaDurationConverterSpec.scala
http-core/src/test/scala/org/apache/pekko/http/javadsl/model/MultipartsSpec.scala
http/src/main/mima-filters/2.0.x.backwards.excludes/javadsl-change-duration-return-types.excludes
http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/TimeoutDirectives.scala
http/src/main/scala/org/apache/pekko/http/scaladsl/server/directives/TimeoutDirectives.scala

follow up to #784 but now we get to change APIs where the return type was wrong (eg a Java DSL that returns a Scala Duration instead of a Java Duration)

breaking Java DSL api changes (Duration)

---

http-core/src/main/scala/org/apache/pekko/http/javadsl/ServerBinding.scala

now that we don't support Scala 2.12, we can use Scala calls directly

don't use pekko.util.JavaDurationConverters

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/parsing/BodyPartParser.scala
http-core/src/main/scala/org/apache/pekko/http/impl/util/HttpConstants.scala

* tries to avoid passing the bytestring twice
* need to debug some broken tests

more performant boundary check

---

docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java
docs/src/test/java/docs/http/javadsl/server/directives/BasicDirectivesExamplesTest.java
docs/src/test/java/docs/http/javadsl/server/directives/FutureDirectivesExamplesTest.java
http-core/src/main/scala/org/apache/pekko/http/impl/engine/server/HttpServerBluePrint.scala
http-core/src/test/scala/org/apache/pekko/http/scaladsl/TestServer.scala
http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/ConnectionTestApp.scala

splitting out some changes from #779

Avoid deprecated code (that will be removed in pekko 2.0.0)

---

http-core/src/main/scala/org/apache/pekko/http/impl/model/UriJavaAccessor.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/Uri.scala

issues like
```
[warn] /home/runner/work/pekko-http/pekko-http/http-core/src/main/scala/org/apache/pekko/http/impl/model/UriJavaAccessor.scala:40:99: Passing an explicit array value to a Scala varargs method is deprecated (since 2.13.0) and will result in a defensive copy; Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call
```

compiler warning about varargs

---

.github/workflows/nightly.yml

I tested pekko-http with jdk 25 and it seemed to work ok

Add JDK 25 to nightly workflow matrix

---

project/plugins.sbt

* the failure in #822 is happening in sbt-hackers-digest and it's not really a core part of our build
* so, at least for now, it seems best to remove it till we can get to the bottom of why it fails
* #823 didn't fix the build

remove remove sbt-hackers-digest

---

http-core/src/main/scala/org/apache/pekko/http/impl/engine/parsing/HttpHeaderParser.scala
http-core/src/main/scala/org/apache/pekko/http/impl/model/parser/CommonActions.scala
http-core/src/main/scala/org/apache/pekko/http/impl/model/parser/UriParser.scala
http-core/src/main/scala/org/apache/pekko/http/impl/util/CharUtils.scala
http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpMessage.scala

current code uses 3 different ways to lowercase a char
* parboiled2 CharUtils method
* an internal method on HttpHeaderParser
* uses Java built-in Character.toLowerCase
I did a jmh benchmark in my pekko-bench project
https://github.com/pjfanning/pekko-bench/blob/main/src/main/scala/example/LowerCaseBench.scala
And this showed that function in HttpHeaderParser was better than or matched the perf of the others on all Java versions.
Parboiled2 was always slower. The Java built-in was as good for Java 21 and 25 but slowest approach in java 17 and below.
This change switches all code to use the pekko-http internal method.

shared character toLowerCase function
