apache/pekko-http

.asf.yaml
Same as: https://github.com/apache/incubator-pekko/commit/f209e3b19cf3ec718973a536dd32c81de8dd890b
=> Divert GitHub notifications

.asf.yaml
This entry is duplicated twice
=> Remove redundant duplicate in .asf.yaml

.github/workflows/validate-and-test.yml
* currently broken - disabling to reduce build noise
* needs to be revisited later
=> disable fossa check

LICENSE
* Lightbend copyright is in NOTICE file
=> use full Apache license

build.sbt, project/plugins.sbt, project/project-info.conf
* relates to https://github.com/apache/incubator-pekko-http/issues/27
=> switch to standard paradox plugin

http-tests/src/multi-jvm/scala/org/apache/pekko/http/PekkoHttpServerLatencyMultiNodeSpec.scala
Seems to be an oversight from renaming
=> fix config in HttpServerLatencyMultiNodeSpec

.github/actions/sync-nightlies/action.yml
=> add sync action necessary for documentation publishing

build.sbt, project/plugins.sbt
Adds sbt source dist, I also tried it locally and can confirm that it works
=> Add sbt source dist

build.sbt, project/ParadoxSupport.scala, project/plugins.sbt
I have tested this locally and everything appears to work (i.e. the new material theme is being used).
=> Use incubator-pekko-sbt-paradox

build.sbt, legal/StandardLicense.txt, project/AddMetaInfLicenseFiles.scala
=> include hpack details in license

docs/src/test/java/docs/http/javadsl/ClientSingleRequestExample.java, docs/src/test/java/docs/http/javadsl/Http2ClientApp.java, docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java, docs/src/test/java/docs/http/javadsl/server/HeaderRequestValsExampleTest.java, docs/src/test/java/docs/http/javadsl/server/HttpBasicAuthenticatorExample.java, docs/src/test/java/docs/http/javadsl/server/OAuth2AuthenticatorExample.java, docs/src/test/java/docs/http/javadsl/server/directives/RespondWithDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/RouteDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/Http2ClientApp.scala, docs/src/test/scala/docs/http/scaladsl/HttpClientCollectingHeaders.scala, docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/HttpClientOutgoingConnection.scala, docs/src/test/scala/docs/http/scaladsl/HttpClientSingleRequest.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/CustomDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/RespondWithDirectivesExamplesSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/client/HttpsProxyGraphStageSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/parsing/HttpHeaderParserSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/parsing/RequestParserSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/parsing/ResponseParserSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/rendering/RequestRendererSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/model/parser/HttpHeaderSpec.scala, http-core/src/test/scala/org/apache/pekko/http/scaladsl/model/HttpMessageSpec.scala, http-core/src/test/scala/org/apache/pekko/http/scaladsl/settings/ConnectionPoolSettingsSpec.scala, http-tests/src/test/java/org/apache/pekko/http/javadsl/HttpAPIsTest.java, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/RouteDirectivesSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/RequestParsingSpec.scala
=> replace usages of akka.io in tests

http-core/src/main/resources/reference.conf
A lot of the other ones seem to be resolved by in-flight PRs. I couldn't find one that handles this case.
=> stray akka ref in conf

project/ParadoxSupport.scala, project/plugins.sbt
=> latest paradox plugin

docs/src/test/resources/application.conf, http-caching/src/main/resources/reference.conf, http-core/src/main/resources/reference.conf, http-core/src/test/resources/reference.conf, http-testkit/src/main/resources/reference.conf, http-tests/src/test/resources/application.conf, http/src/main/resources/reference.conf, project/CopyrightHeader.scala
and fix up some stray akka refs in those files
relates to https://github.com/apache/incubator-pekko/pull/227
=> add license headers to conf files

project/CopyrightHeader.scala
same issue as https://github.com/apache/incubator-pekko-connectors/pull/33
=> can only set headerLicense once

.scala-steward.conf
=> fix scala-steward configuration

project/Publish.scala, project/plugins.sbt
Replaces ci-release with dynver, see https://lists.apache.org/thread/l7yp8yb2ooy7opwmzpw7hkmz9gm0qr2r
=> Replace ci-release with dynver

.github/workflows/publish.yml
The previous fix in #118 did not work.
=> fix nightly publishing

project/Dependencies.scala
=> Update Scala 2.12 version

project/Dependencies.scala
follow up to https://github.com/apache/incubator-pekko/pull/273
=> upgrade to jackson 2.14.2

project/PekkoDependency.scala
relates to jackson upgrade in pekko
=> upgrade pekko dependency

http-scalafix/scalafix-test-input/src/main/scala/org/apache/pekko/http/fix/MigrateToServerBuilderTest.scala, http-scalafix/scalafix-test-output/src/main/scala/org/apache/pekko/http/fix/MigrateToServerBuilderTest.scala
some files I found without license headers
=> missing license headers

build.sbt, project/plugins.sbt
a couple of minor plugin bumps too
=> add license headers to sbt files

project/Dependencies.scala
=> Update Scala 2 versions

project/PekkoDependency.scala
with a Pekko Core RC coming soon, it is important to verify everything
=> use latest pekko snapshot

http-core/src/main/scala/org/apache/pekko/http/impl/util/SocketOptionSettings.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/HttpServerBug21008Spec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/HttpServerSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/server/HttpServerWithExplicitSchedulerSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/WebSocketServerSpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/BasicRouteSpecs.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/TestServer.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/MarshallingDirectivesSpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/ParameterDirectivesSpec.scala, http/src/main/scala/org/apache/pekko/http/javadsl/unmarshalling/Unmarshaller.scala, http/src/main/scala/org/apache/pekko/http/scaladsl/server/directives/RouteDirectives.scala, http/src/main/scala/org/apache/pekko/http/scaladsl/server/directives/SecurityDirectives.scala, http/src/main/scala/org/apache/pekko/http/scaladsl/unmarshalling/MultipartUnmarshallers.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/H2cUpgradeSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2ClientSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2ServerDemuxSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/ProtocolSwitchSpec.scala
Low hanging fruit safe to apply fixes from scalac warnings from various Scala versions
=> Fix low hanging fruit from warnings

README.md
* copied from https://github.com/apache/incubator-pekko
* in anticipation that this repo will soon head to RC
=> add build docs

http-core/src/main/scala/org/apache/pekko/http/impl/util/StageLoggingWithOverride.scala
tidier to link to the pekko code
The Incubator PMC are searching for code for any links like this and they are causing us trouble with getting releases done.
=> use link to pekko code

docs/src/test/scala/docs/http/scaladsl/Http2ClientApp.scala, http-core/src/main/scala/org/apache/pekko/http/impl/util/StageLoggingWithOverride.scala
* some akka links that have been broken by partially applying pekko renaming
=> fix some broken links

project/plugins.sbt
contains a change to the zip/tgz directory structure
=> sbt-source-dist 0.1.6

build.sbt, project/PekkoDependency.scala
useful to try the pekko rc2 jars in automated builds
=> test with pekko rc2

LICENSE
=> add LICENSE bit about Tim Kienzle code

project/plugins.sbt
see https://github.com/apache/incubator-pekko/pull/458
=> Update paradox plugin

build.sbt
=> use generic snapshot link for snapshot scaladoc/javadoc

docs/src/test/java/docs/http/javadsl/server/cors/CorsServerExample.java, docs/src/test/scala/docs/http/scaladsl/server/cors/CorsServerExample.scala
Fix #217.
Not sure what's the most simple/idiomatic for the `main` method, I mostly copied what I found in other examples. 
Review by @mdedetrich
=> Remove deprecated usage of HttpApp in CorsServerExample

project/build.properties, project/plugins.sbt
* latest changes to our source distribution format
=> upgrade source dist plugin

docs/src/test/scala/docs/http/scaladsl/server/cors/CorsServerExample.scala
=> Fix FQCN imports

project/Dependencies.scala
Match version used in Pekko (core)
=> scalatest 3.2.14

project/AddMetaInfLicenseFiles.scala, project/CopyrightHeader.scala, project/LicenseReport.scala
Same as https://github.com/apache/incubator-pekko/pull/474 but for this repo
=> Apply normal apache header new files

build.sbt
see https://github.com/apache/incubator-pekko/pull/468
=> source dist name

project/plugins.sbt
This will bring in the newly updated incubator logo which we were asked to use
=> Update latest pekko-sbt-paradox

README.md
see https://github.com/apache/incubator-pekko-http/issues/218#issuecomment-1648476214
=> update note about h2spec

.github/workflows/publish-1.0-docs.yml
* typo in yml is causing job to fail
* relates to #273
=> fix issue in publish-1.0-docs.yml

project/plugins.sbt
So its easier to verify future builds
=> Update sbt-reproducible-builds and set check resolver to staging

build.sbt
Forgot to do this in https://github.com/apache/incubator-pekko-http/pull/277
=> Set reproducibleBuildsCheckResolver to staging

build.sbt, project/AddMetaInfLicenseFiles.scala, project/AutomaticModuleName.scala, project/CliOptions.scala, project/Common.scala, project/CopyrightHeader.scala, project/Dependencies.scala, project/Doc.scala, project/GitHub.scala, project/MiMa.scala, project/MultiNode.scala, project/NoScala3.scala, project/ParadoxSupport.scala, project/PekkoDependency.scala, project/Pre213Preprocessor.scala, project/Publish.scala, project/Untar.scala, project/ValidatePullRequest.scala, project/VersionGenerator.scala
Equivalent of https://github.com/apache/incubator-pekko/pull/511 but for this project
=> Remove org.apache.pekko package from sbt build

.scala-steward.conf
some of the versions are out of date
=> update pinned versions in .scala-steward.conf

http-core/src/test/scala/org/apache/pekko/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala
Update LowLevelOutgoingConnectionSpec.scala
=> remove assertions about akka 2.5

.github/workflows/nightly.yml, project/PekkoDependency.scala
=> test with 1.1 snapshot

project/Dependencies.scala
It should be `contains` or `endWith`.
=> =sbt Fix sbt loading on Windows.

.github/workflows/format.yml
1.0.x branch is the target for this PR
=> update format check to use 1.0.x branch

project/plugins.sbt
cherry pick 6781b5a7e10eebae67dcd0cbdac8c5fa028126c0
=> backport: use sbt paradox release

.github/workflows/format.yml, .github/workflows/headers.yml, .github/workflows/link-validator.yml, .github/workflows/nightly.yml, .github/workflows/publish-1.0-docs.yml, .github/workflows/publish.yml, .github/workflows/validate-and-test.yml
(cherry picked from commit 57dcb5dcc64b4c269d83a01909a7a39dcd32bf71)
=> Use fetch tags from latest checkout action

.github/workflows/format.yml
Accident from previously created PR
=> Remove unnecessary fetch-tags

project/build.properties
(cherry picked from commit 4eccd171aceeaa4d79c01b73b1276f9b4873b63f)
=> Update SBT to 1.9.6

project/PekkoDependency.scala
(cherry picked from commit 9de3848d1c2afd101647e4c75007f480f76afbe4)
=> Set minimumExpectedPekkoVersion to 1.0.0

.github/workflows/scala-steward.yml, .scala-steward.conf
=> Add scala-steward

.github/workflows/nightly.yml
(cherry picked from commit 17da94039e5b63d2be8f73cfac673e2a6f8517ca)
=> test with LTS JDK 21 (#335)

project/plugins.sbt
not sure why scala steward is not creating plugin upgrade PRs in this repo
=> sbt-source-dist 0.1.11

project/plugins.sbt
https://developer.android.com/build/jcenter-migration
=> remove jcenter - it is deprecated

project/plugins.sbt
cherry pick efa8c8e14a350f9d288ed1a88df633d1de609498
=> sbt-source-dist 0.1.11 (#338)

docs/src/main/paradox/.htaccess, http-core/src/main/java/org/apache/pekko/http/javadsl/model/headers/HttpCookie.java, http-core/src/main/scala/org/apache/pekko/http/scaladsl/settings/ConnectionPoolSettings.scala, project/Doc.scala
a few version numbers lacking Akka prefixing
=> prefix Akka HTTP versions

docs/src/main/paradox/.htaccess, http-core/src/main/java/org/apache/pekko/http/javadsl/model/headers/HttpCookie.java, http-core/src/main/scala/org/apache/pekko/http/scaladsl/settings/ConnectionPoolSettings.scala, project/Doc.scala
cherry pick 6df57df1c46c0d3b90cca2bd21ad107ced354043
=> prefix Akka HTTP versions (#342)

.scala-steward.conf
Pin the java formatter to 0.7.0
=> Pin sbt-java-formatter to 0.7.0

build.sbt, project/PekkoDependency.scala
=> Minor refactoring variable name consistent

http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/ConnectionPoolBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/HttpEntityBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/ServerProcessingBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/StreamServerProcessingBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/http2/H2ClientServerBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/http2/H2ServerProcessingBenchmark.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/client/HostConnectionPoolSpec.scala, http/src/main/java/org/apache/pekko/http/javadsl/server/HttpApp.java, http/src/main/scala/org/apache/pekko/http/scaladsl/server/HttpApp.scala
=> akka to pekko naming

http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/ConnectionPoolBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/HttpEntityBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/ServerProcessingBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/StreamServerProcessingBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/http2/H2ClientServerBenchmark.scala, http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/http2/H2ServerProcessingBenchmark.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/client/HostConnectionPoolSpec.scala, http/src/main/java/org/apache/pekko/http/javadsl/server/HttpApp.java, http/src/main/scala/org/apache/pekko/http/scaladsl/server/HttpApp.scala
cherry pick 72221db4531fc3c4b6b6f461de37a2378b927a5b
=> akka to pekko naming (#348)

http-compatibility-tests/src/test/scala/org/apache/pekko/http/scaladsl/HostConnectionPoolCompatSpec.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/PoolMasterActor.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/pool/SlotState.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/server/ServerTerminator.scala, http-core/src/main/scala/org/apache/pekko/http/javadsl/ServerBinding.scala, http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/ConnectionPoolSettings.scala, http-core/src/test/scala/org/apache/pekko/http/impl/model/parser/HttpHeaderSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/util/PekkoSpecWithMaterializer.scala, http-core/src/test/scala/org/apache/pekko/http/scaladsl/ClientServerSpec.scala, http-core/src/test/scala/org/apache/pekko/http/scaladsl/GracefulTerminationSpec.scala, http-core/src/test/scala/org/apache/pekko/testkit/PekkoSpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/RoutingSpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/IllegalHeadersIntegrationSpec.scala, http/src/main/scala/org/apache/pekko/http/javadsl/marshalling/Marshaller.scala, http/src/main/scala/org/apache/pekko/http/scaladsl/marshalling/Marshaller.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2ClientSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2PersistentClientSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2ServerSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/RequestParsingSpec.scala
cherry pick 8815ed47a7f71f7e6f011b3de403f69cd3bb8748
=> fix more akka naming (#354)

project/Dependencies.scala
cherry pick 2732faa0f01412d317255d7ede22d82a0c627bf5
=> =sbt Update to Scala 3.3.1

build.sbt
jcenter has been sunset
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
=> remove jcenter resolver

docs/src/main/paradox/introduction.md, docs/src/main/paradox/routing-dsl/index.md, http/src/main/java/org/apache/pekko/http/javadsl/server/HttpApp.java, http/src/main/scala/org/apache/pekko/http/scaladsl/server/HttpApp.scala
cherry pick 61a7dd37f4f5d7b7504104c12f784e2114134c6b #372
=> use asf giter8 templates (#372)

project/plugins.sbt
sbt-scalafix:0.11.1 is released
and I can't build with 0.11.0
=> update version of sbt-scalafix to 0.11.1

docs/src/main/paradox/common/cors.md
cherry pick a33131d3949720bee08f36d9cce466216eb59c3c #385
=> try to fix scala/java issue with CORS page (#385)

docs/src/main/paradox/common/cors.md
cherry pick cd6039fc15de55b12a01fef3fb531f69f5c57142 #386
=> fix todo link in CORS doc (#386)

.github/workflows/scala-steward.yml
References: https://github.com/apache/incubator-pekko-http/issues/379, see https://github.com/scala-steward-org/scala-steward/issues/3257#issuecomment-1872788986
=> Fix scala-steward updating incorrect repo's

NOTICE, legal/CorsNotice.txt, legal/PekkoNotice.txt
cherry pick 8a009e01d98805263560acb5bfad641de75f6cc5 #391
=> add 2024 to copyright (#391)

.scala-steward.conf
See https://github.com/apache/incubator-pekko-http/pull/404 and https://github.com/apache/incubator-pekko-http/pull/403
=> Update and fix ignored updates for sbt-paradox

.github/workflows/format.yml
(cherry picked from commit a66000d0f481a71bf36ecb1cb24e97e25d7d0eaa)
=> Update scalafmt-native github action and remove hardcoded version

http-core/src/main/java/org/apache/pekko/http/javadsl/model/Authority.java, http-core/src/main/java/org/apache/pekko/http/shaded/com/twitter/hpack/HuffmanEncoder.java, http-core/src/main/java/org/apache/pekko/http/shaded/com/twitter/hpack/StaticTable.java, http-tests/src/main/java/org/apache/pekko/http/javadsl/server/examples/simple/SimpleServerApp.java
Motivation:
When run idea code inspection, I found some of these
Result:
less problem
=> chore:Fix some code inspection errors.

build.sbt, project/PekkoCoreDependency.scala, project/VersionGenerator.scala, project/plugins.sbt
* enable compile inline
* Update PekkoCoreDependency.scala
* set pekkoInlineEnabled explicitly
(cherry picked from commit 8d9455f46ba33ff30e35cd017cdce9fa5c5f2d43)
=> upgrade sbt-pekko-build (#418)

docs/src/test/java/docs/http/javadsl/server/directives/FileUploadDirectivesExamplesTest.java, http-core/src/main/java/org/apache/pekko/http/shaded/com/twitter/hpack/HpackUtil.java, http-core/src/main/scala/org/apache/pekko/http/impl/engine/ws/MessageToFrameRenderer.scala, http-core/src/main/scala/org/apache/pekko/http/impl/util/package.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/ws/WSTestUtils.scala, http-core/src/test/scala/org/apache/pekko/http/impl/util/RenderingSpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/unmarshalling/UnmarshallingSpec.scala
use constants instead of deriving it from a text value
=> use StandardCharsets

http-bench-jmh/src/main/scala/org/apache/pekko/http/impl/engine/http2/H2ClientServerBenchmark.scala, http-core/src/main/mima-filters/1.0.x.backwards.excludes/http2-rapid-reset-configs.backwards.excludes, http-core/src/main/resources/reference.conf, http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/Http2Blueprint.scala, http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/Http2ServerSettings.scala, http-core/src/main/scala/org/apache/pekko/http/scaladsl/settings/Http2ServerSettings.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2BlueprintSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/util/WithLogCapturing.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2ServerDisableFrameTypeThrottleSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2ServerEnableFrameTypeThrottleSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2ServerSpec.scala, http2-tests/src/test/scala/org/apache/pekko/http/impl/engine/http2/Http2SpecWithMaterializer.scala
cherry pick da6a228372efac2da05aae68c3acb982f7a7e58d #394
=> Http2 frame type throttle (#394)

NOTICE, legal/CorsNotice.txt, legal/PekkoNotice.txt
see https://github.com/apache/incubator-pekko/pull/1009
=> add incubating to NOTICE

scripts/link-validator.conf
see https://github.com/apache/incubator-pekko-http/actions/runs/7600957636/job/20699787636
=> add extra http exception to link-validator.conf

NOTICE, legal/CorsNotice.txt, legal/PekkoNotice.txt
cherry pick b540247ce9976b3bbd544d508da7be15e43e0bf4 #428
=> add incubating to NOTICE (#428)

.asf.yaml, .github/workflows/dependency-graph.yml
Sets up dependabot to give alerts whenever there are security issues
=> Setup dependabot for alerts

.github/workflows/dependency-graph.yml
See https://github.com/apache/incubator-pekko-http/actions/runs/7621313379/job/20757511382
=> Add pekko-http-docs_3 to dependency graph modules-ignore

.github/workflows/dependency-graph.yml
=> Fix dependency submission

build.sbt, project/plugins.sbt
See https://github.com/pjfanning/sbt-pekko-build/pull/8 for context
=> Updates sbt-pekko-build

http-tests/src/test/resources/dirWithLink/linked-dir, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/directives/FileAndResourceDirectivesSymlinkSpec.scala
cherry pick c231269c72f4a95e28bada1bbcddc0cf396ee17a #445
=> rework symlink test (#445)

.github/workflows/nightly.yml, .github/workflows/publish-1.0-snapshots.yml, .github/workflows/publish.yml
Motivation:
Streamling the build.
=> chore: Schedule the build at 1.30 AM

project/MultiNode.scala
=> Fix deprecation warnings for MultiJvm plugin

project/plugins.sbt
(cherry picked from commit e503a25d1bcdd6dc7a6819788be6e01fc2c33e1e)
=> Update sbt-pekko-build to 0.3.3

build.sbt
=> Fix deprecated import

.github/workflows/publish-1.0-docs.yml
part of Pekko HTTP 1.0.1 release
=> 1.0.1 docs

docs/src/main/paradox/release-notes/index.md
cherry pick 1c63d94fae584e2c3c98f17ff6e84f388294a9dd #442
=> release notes for v1.0.1 (#442)

.github/workflows/link-validator.yml
Job is running into GC issues because it is running with constrained heap memory
=> mem settings for link-validator.yml

project/plugins.sbt
* might fail due to java 8 build issues
* passed on my laptop - which surprised me
=> upgrade paradox plugins

build.sbt, scripts/link-validator.conf
cherry pick 8b4f23c7de034e3277938dc216737515f1158402 #496
=> fix api/japi links in build.sbt (#496)

project/Dependencies.scala
Co-authored-by: scala-steward-asf[bot] <147768647+scala-steward-asf[bot]@users.noreply.github.com>
(cherry picked from commit f43f1cb81d3f061b93e8e5c00f042d0f25f79716)
=> Update scala3-library to 3.3.3 (#502)

project/Dependencies.scala
Co-authored-by: scala-steward-asf[bot] <147768647+scala-steward-asf[bot]@users.noreply.github.com>
(cherry picked from commit 3ca37a419ecd8ed23f10de6fe331ad0e5e26004b)
=> Update scala-library, scala-reflect to 2.12.19 (#491)

NOTICE, legal/CorsNotice.txt
=> remove incubating from notice

NOTICE, legal/CorsNotice.txt
cherry pick 343cfc07bdc1fbdf94eacf29387880c52f1e3062 #522
=> remove incubating from notice (#522)

project/ParadoxSupport.scala
see https://github.com/apache/pekko/pull/1216
=> remove incubator footer

project/ParadoxSupport.scala
cherry pick b6263de8c5582e096bfc5cdd969576d8de438237 #525
=> remove incubator footer (#525)

.github/workflows/scala-steward.yml
=> Add workflow dispatch plus repo condition to scala-steward.yml

docs/src/main/paradox/routing-dsl/directives/debugging-directives/logRequest.md, docs/src/main/paradox/routing-dsl/directives/debugging-directives/logRequestResult.md, docs/src/main/paradox/routing-dsl/directives/debugging-directives/logResult.md, docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFields.md, docs/src/main/paradox/routing-dsl/directives/future-directives/onSuccess.md, docs/src/main/paradox/routing-dsl/directives/header-directives/headerValueByType.md, docs/src/main/paradox/routing-dsl/directives/header-directives/optionalHeaderValueByType.md, docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameters.md, docs/src/main/paradox/routing-dsl/directives/range-directives/withRangeSupport.md, docs/src/main/paradox/routing-dsl/directives/route-directives/complete.md
cherry pick f998dde534f7e06d75101418ec488f7f517c94ec #542
=> use different article because spray.io is dead (#542)

build.sbt, http-scalafix/README.md
see https://github.com/apache/pekko/pull/1312
=> scalafixScalaBinaryVersion setting no longer needed

.scala-steward.conf, http-marshallers-java/http-jackson/src/main/resources/reference.conf, project/Dependencies.scala
see https://github.com/apache/pekko/pull/1318
=> jackson 2.17

project/PekkoCoreDependency.scala
see https://github.com/apache/pekko-http/issues/419
=> build with pekko 1.1

http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpHeader.scala, http-core/src/test/scala/org/apache/pekko/http/impl/model/parser/HttpHeaderSpec.scala
* also tidy up test name from #574 - the 'should' is already picked up from code wrapping this test
=> remove unnecessary interpolation

build.sbt, project/PekkoCoreDependency.scala
=> use pekko 1.1.0

docs/src/main/paradox/migration-guide/index.md, docs/src/main/paradox/routing-dsl/directives/security-directives/index.md
see https://github.com/apache/pekko-connectors-kafka/pull/224
=> broken migration guide link

.github/workflows/publish-1.1-docs.yml, docs/src/main/paradox/release-notes/releases-1.1.md
=> release notes for v1.1.0

docs/src/main/paradox/release-notes/index.md
=> fix akka security link

.github/workflows/publish-1.1-docs.yml, .github/workflows/publish-1.1-snapshots.yml
needed since #631 merged and main branch now being a 1.2.x dev branch
=> publish 1.1 snapshots and 1.1 docs based on 1.1.x branch

http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/HttpsProxyGraphStage.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/OutgoingConnectionBlueprint.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/client/pool/NewHostConnectionPool.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/Http2Multiplexer.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/Http2StreamHandling.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/ProtocolSwitch.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/client/PersistentConnection.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/rendering/HttpRequestRendererFactory.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/rendering/HttpResponseRendererFactory.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/server/HttpServerBluePrint.scala, http-core/src/main/scala/org/apache/pekko/http/impl/util/One2OneBidiFlow.scala, http-core/src/main/scala/org/apache/pekko/http/impl/util/StreamUtils.scala, http-core/src/test/java/org/apache/pekko/http/javadsl/WSEchoTestClientApp.java, http-core/src/test/scala/org/apache/pekko/http/impl/engine/client/HostConnectionPoolSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/client/NewConnectionPoolSpec.scala, http-core/src/test/scala/org/apache/pekko/http/impl/engine/parsing/RequestParserSpec.scala, http-core/src/test/scala/org/apache/pekko/http/scaladsl/model/HttpEntitySpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/EntityStreamingSpec.scala
Replaces some deprecated stuff
=> Fix some compiler warnings

http-core/src/main/mima-filters/1.2.x.backwards.excludes/content-media-type-value-string.backwards.excludes
=> missing asf header

scripts/link-validator.conf
failing on basically every CI run now
https://github.com/apache/pekko-http/actions/workflows/link-validator.yml
=> issues with stackoverflow links in CI runs

project/Dependencies.scala
not sure why scala steward skipped this
=> jackson 2.18.4

build.sbt, project/PekkoCoreDependency.scala
=> test with pekko 1.1.4

.scala-steward.conf, project/Dependencies.scala
=> jackson 2.19.1

build.sbt, project/PekkoCoreDependency.scala
=> test with pekko 1.1.5

docs/src/main/paradox/security.md
cherry pick e7d706a8d5680e7bd38bd29053cf6520a3497aea #722 
Needs to be in a branch like 1.2.x to end up in our docs for released versions - as opposed to the nightly docs for the snapshot versions
=> docs: add basic security model (#722)

http-core/src/main/scala/org/apache/pekko/http/impl/model/JavaUri.scala, http-core/src/main/scala/org/apache/pekko/http/impl/model/UriJavaAccessor.scala, http-core/src/main/scala/org/apache/pekko/http/impl/util/JavaMapping.scala, http-core/src/main/scala/org/apache/pekko/http/javadsl/settings/Http2ServerSettings.scala, http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpCharset.scala, http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpMessage.scala, http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/MediaRange.scala, http-core/src/main/scala/org/apache/pekko/http/scaladsl/settings/Http2ServerSettings.scala, http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/FormFieldDirectives.scala, http/src/main/scala/org/apache/pekko/http/javadsl/server/directives/HeaderDirectives.scala, http/src/main/scala/org/apache/pekko/http/scaladsl/unmarshalling/Unmarshaller.scala
* a few cases missing from #771
=> use Scala converters in more places

http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/Http2Multiplexer.scala, http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/RequestParsing.scala
code it relates to was removed
=> remove outdated nowarn annotation

http-core/src/main/scala/org/apache/pekko/http/javadsl/ServerBinding.scala, http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/HttpMessage.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/server/RejectionSpec.scala, http-tests/src/test/scala/org/apache/pekko/http/scaladsl/unmarshalling/sse/EventStreamUnmarshallingSpec.scala, http/src/main/scala/org/apache/pekko/http/javadsl/marshalling/sse/EventStreamMarshalling.scala, http/src/main/scala/org/apache/pekko/http/javadsl/unmarshalling/sse/EventStreamUnmarshalling.scala
related to https://github.com/apache/pekko-grpc/pull/522
=> try to remove unnecessary map calls

http-marshallers-java/http-jackson/src/main/java/org/apache/pekko/http/javadsl/marshallers/jackson/Jackson.java
Not definitely the cause of #822 but just before the failure we get a verbose warning about this class not having Javadoc.
=> add javadoc to Jackson.java
